# Generated by Django 5.2.7 on 2025-10-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Formulas',
            fields=[
                ('idform', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('folio', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.FloatField()),
                ('tolerancia', models.IntegerField()),
            ],
            options={
                'db_table': 'Formulas',
                'managed': False,
            },
        ),
    ]
