# Generated by Django 5.2.7 on 2025-11-05 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Formulas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_Formula',
            fields=[
                ('iddetalle', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'Detalle_Formula',
                'managed': False,
            },
        ),
    ]
