# Generated by Django 5.2.7 on 2025-10-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operadores',
            fields=[
                ('rfid', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'Operadores',
                'managed': False,
            },
        ),
    ]
