# Generated by Django 5.2.7 on 2025-10-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Estaciones',
            fields=[
                ('idest', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('obs', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Estaciones',
                'managed': False,
            },
        ),
    ]
