# Generated by Django 5.2.7 on 2025-10-24 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredientes',
            fields=[
                ('iding', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('presentacion', models.FloatField()),
                ('observaciones', models.CharField(max_length=50)),
                ('pesado', models.BooleanField()),
            ],
            options={
                'db_table': 'Ingredientes',
                'managed': False,
            },
        ),
    ]
