# Generated by Django 5.2.7 on 2025-11-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produccion',
            fields=[
                ('folio', models.AutoField(primary_key=True, serialize=False)),
                ('op', models.CharField(max_length=20)),
                ('lote', models.CharField(max_length=50)),
                ('pesform', models.FloatField()),
                ('pesing', models.FloatField()),
                ('pmax', models.FloatField()),
                ('pmin', models.FloatField()),
                ('pesado', models.IntegerField()),
                ('estatus', models.IntegerField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'Produccion',
                'managed': False,
            },
        ),
    ]
