# Generated by Django 5.2.7 on 2025-11-21 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Produccion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleProduccion',
            fields=[
                ('iddetalleproduccion', models.AutoField(primary_key=True, serialize=False)),
                ('pesing', models.FloatField(blank=True, null=True)),
                ('pmax', models.FloatField(blank=True, null=True)),
                ('pmin', models.FloatField(blank=True, null=True)),
                ('pesado', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Detalle_Produccion',
                'managed': False,
            },
        ),
    ]
