"""
Django settings for formulacion_project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-cdhd0ao$s(4-er(@+iq59*5%4a+q7sdfro!gbg=z!n*@t)zzs5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    #'rest_framework.authtoken',
    'corsheaders',
    'Dashboard',
    'Estaciones',
    'Empresa',
    'Formulas',
    'Ingredientes',
    'Inventario',
    'Login',
    'Operadores',
    'Produccion',
    'Usuarios',

]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        # Definimos JWT como el método de autenticación principal
        'rest_framework_simplejwt.authentication.JWTAuthentication',
        # Puedes mantener el SessionAuthentication para el navegador
        'rest_framework.authentication.SessionAuthentication', 
    ),
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'formulacion_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True, 
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'formulacion_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases


""" 
#OPCION 1. PARA USO DE BASE DE DATOS MEDIANTE AUTENTICACION CON WINDOWS

DATABASES = {
    'default': {
        'ENGINE': 'mssql', #POR DEFECTO
        'NAME': 'SOFte', #NOMBRE DE LA BASE DE DATOS A USAR
        'USER' : '', #VACIO POR DEFECTO (AUTENTICACION POR WINDOWS)
        'PASSWORD' : '', #VACIO POR DEFECTO (AUTENTICACION POR WINDOWS)
        'HOST': 'ISAÍ',  #NOMBRE DEL SERVER (SERVER NAME)
        'PORT': '', #VACIO POR DEFECTO (AUTENTICACION POR WINDOWS)
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
        },
    }
}
"""

#OPCION 2. PARA USO DE BASE DE DATOS MEDIANTE USUARIO Y CONTRASEÑA
DATABASES = {
    'default': {
        'ENGINE': 'mssql',
        'NAME': 'SOFte',               # Nombre de tu base de datos
        'USER': 'django_user',        # Usuario SQL 
        'PASSWORD': '3541587873',  # Contraseña del usuario
        'HOST': 'localhost',           # O el nombre del servidor (server name)
        'PORT': '1433',                # Puerto por defecto de SQL Server
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'extra_params': 'TrustServerCertificate=yes;Encrypt=no',
        },
    }
}



# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173", # La dirección por defecto de Vite
    "http://127.0.0.1:5173", # A veces el navegador usa esta IP en lugar de 'localhost'
]

CORS_ALLOW_ALL_ORIGINS = True

MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

AUTH_USER_MODEL = 'Usuarios.Usuario'
DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

SIMPLE_JWT = {
    # 1. Access Token: el token que se usa para las peticiones API
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),  # Dura 1 hora 
    # 2. Refresh Token: se usa para obtener un nuevo Access Token
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),     # Dura 1 día

    # 3. Al usar un refresh invalida el token anterior
    'ROTATE_REFRESH_TOKENS': True, 
    
    # 4. Obliga al cliente a usar el nuevo token de forma inmediata
    'BLACKLIST_AFTER_ROTATION': True,

    # 3. Permite usar el ID de usuario personalizado (tu rfid/correo) en el token
    # Necesario para saber qué usuario está pidiendo el token.
    'USER_ID_FIELD': 'correo',
    'USER_ID_CLAIM': 'correo',
    
    'AUTH_HEADER_TYPES': ('Bearer',), # El frontend enviará "Authorization: Bearer <token>"

}