# Generated by Django 5.2.7 on 2025-11-19 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('folio', models.IntegerField(primary_key=True, serialize=False)),
                ('op', models.CharField(max_length=20)),
                ('lform', models.CharField(max_length=50)),
                ('pobj', models.FloatField()),
                ('preal', models.FloatField()),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'Inventario',
                'managed': False,
            },
        ),
    ]
