# Generated by Django 5.2.7 on 2025-11-21 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inventario', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Inventario',
        ),
    ]
