# Generated by Django 5.2.7 on 2025-10-16 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('rfid', models.UUIDField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('correo', models.CharField(max_length=50)),
                ('contraseña', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Usuarios',
                'managed': False,
            },
        ),
    ]
